[[redirects]]
  from = "/imd@"
  to = "/imd@/index.html"
  status = 200

[[redirects]]
  from = "/resources"
  to = "/learn"

[[redirects]]
  from = "/contact"
  to = "https://www.form.gov.sg/635f32c5001b2d0011fff09b"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  ignore = "git log -1 --pretty=%B | grep dependabot"

# Unset the infura key with domain restriction for branch previews
# so that the default key (without domain restriction) is used instead
[context.deploy-preview]
  [context.deploy-preview.environment]
    INFURA_API_KEY = ""

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"
    Content-Security-Policy = "default-src 'self'; img-src 'self'; style-src 'self' https://fonts.googleapis.com https://use.fontawesome.com 'unsafe-inline'; script-src 'self' https://identity.netlify.com https://www.googletagmanager.com 'unsafe-inline' 'unsafe-eval'; font-src 'self' data: https://fonts.gstatic.com https://use.fontawesome.com https://ui.tradetrust.io; connect-src 'self' https://www.google-analytics.com https://identity.netlify.com https://*.infura.io/v3/ https://dns.google https://cloudflare-dns.com https://min-api.cryptocompare.com https://api.blocknative.com; frame-src * https://app.netlify.com; frame-ancestors 'self'; object-src 'none';"
