[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  ACCESS_TOKEN = ${PRODUCTION_INFURA_KEY}

[context.deploy-preview.environment]
  ACCESS_TOKEN = ${PREVIEW_INFURA_KEY}
