backend:
  name: git-gateway
  branch: master

local_backend: true

publish_mode: editorial_workflow

media_folder: "static/uploads"
public_folder: "/static/uploads"

collections:
  - name: "faq-page"
    label: "FAQ Page"
    folder: "cms/faq-page"
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string", hint: "This is used for the page title" }
      - { label: "Body", name: "body", widget: "markdown", hint: "This is the body text." }
