backend:
  name: git-gateway
  branch: master
  squash_merges: true
  commit_messages:
    create: "feat: Create {{collection}} “{{slug}}” {{author-name}}"
    update: "chore: Update {{collection}} “{{slug}}” {{author-name}}"
    delete: "chore: Delete {{collection}} “{{slug}}” {{author-name}}"
    uploadMedia: "chore: Upload “{{path}}” {{author-name}}"
    deleteMedia: "chore: Delete “{{path}}” {{author-name}}"

local_backend: true

publish_mode: editorial_workflow

media_folder: "public/static/uploads"
public_folder: "/static/uploads"

collections:
  - name: "faq"
    label: "FAQ"
    folder: "cms/faq"
    create: true
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string", hint: "Title of FAQ question." }
      - { label: "Body", name: "body", widget: "markdown", hint: "Body text of FAQ answer." }
      - {
          label: "Published Date",
          name: "publishedDate",
          widget: "datetime",
          time_format: "HH:mm",
          hint: "Published date, doubling up as sequence order.",
        }
    sortable_fields: ["title", "publishedDate"]
  - name: "newsletter"
    label: "Newsletter"
    folder: "cms/newsletter"
    create: true
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string", hint: "Title of newsletter." }
      - { label: "File", name: "file", widget: "file", hint: "File download of newsletter." }
  - name: "media"
    label: "Media"
    folder: "cms/media"
    create: true
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string", hint: "Title the media article." }
      - { label: "Date", name: "date", widget: "date", format: "D MMM YYYY", hint: "Publish date of media article." }
      - { label: "Link", name: "link", widget: "string", hint: "Url of media article." }
  - name: "event"
    label: "Event"
    folder: "cms/event"
    create: true
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string", hint: "Title of event." }
      - { label: "Thumbnail", name: "thumbnail", widget: "image", required: false }
      - { label: "Description", name: "description", widget: "text", hint: "Short description of event." }
      - { label: "Link", name: "link", widget: "string", hint: "Link of event." }
      - { label: "Date", name: "date", widget: "date", format: "D MMM YYYY", hint: "Date of event." }
      - {
          label: "Time Start",
          name: "timeStart",
          widget: "datetime",
          date_format: false,
          time_format: "HH:mm",
          required: false,
          hint: "Start time of event.",
          default: "",
        }
      - {
          label: "Time End",
          name: "timeEnd",
          widget: "datetime",
          date_format: false,
          time_format: "HH:mm",
          required: false,
          hint: "End time of event.",
          default: "",
        }
      - { label: "Video Link", name: "videoLink", widget: "string", required: false, hint: "Video link of event." }
      - { label: "Slides", name: "slides", widget: "file", required: false, hint: "Presentation slides of event." }
      - {
          label: "Register Link",
          name: "registerLink",
          widget: "string",
          required: false,
          hint: "Video link of event.",
        }
