name: CI

on: [push]

jobs:
  test:
    name: Lint & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Cache Node Modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install Packages
        # there's a problem with ganache-core using a very old version of ethereumjs-abi which fails on git checkout with ssh reasons
        run: |
          git config --global url."https://".insteadOf git://
          git config --global url."https://".insteadOf git+https://
          git config --global url."https://".insteadOf ssh://git
          npm ci
        env:
          CYPRESS_CACHE_FOLDER: ${{ github.workspace }}/node_modules/.cache/Cypress
      - name: Check Lint
        run: npm run lint
      - name: Test
        if: ${{ !contains(github.event.head_commit.message, '[skip test]') }}
        run: npm run test
      - name: Build
        run: npm run build:test
      - name: Integration - testcafe
        id: testcafe
        if: ${{ !contains(github.event.head_commit.message, '[skip test]') }}
        run: npm run integration:headless
        continue-on-error: true
      - name: 'Upload Artifact'
        if: ${{ failure() && steps.testcafe.outcome == 'failure' }}
        uses: actions/upload-artifact@v3
        with:
          name: testcafe-fail-screenshots
          path: artifacts
          if-no-files-found: ignore
          retention-days: 5
  synpress-run:
    name: Synpress e2e test
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
      - name: Synpress run
        uses: cypress-io/github-action@v2
      - name: Integration - Synpress
        if: ${{ !contains(github.event.head_commit.message, '[skip test]') }}
        env:
          CYPRESS_CACHE_FOLDER: ${{ github.workspace }}/node_modules/.cache/Cypress
        run: npm run integration:headful
