name: Testcafe

on: [push]

jobs:
  testcafe:
    name: Testcafe e2e Test
    runs-on: ubuntu-latest
    steps:
      - name: Check skip condition
        run: |
          if [[ ${{ contains(github.event.head_commit.message, '[skip test]') }} ]]; then
            echo "Condition met. Exit 0 early with success."
            exit 0
          else
            echo "Condition not met. Continue with test."
          fi
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "14"
      - name: Install Packages
        run: npm ci
      - name: Build
        run: npm run build:test
      - name: Integration - testcafe
        id: testcafe
        run: npm run integration:testcafe:ci
      - name: Upload Artifact
        if: ${{ failure() && steps.testcafe.outcome == 'failure' }}
        uses: actions/upload-artifact@v3
        with:
          name: testcafe-fail-screenshots
          path: artifacts
          if-no-files-found: ignore
          retention-days: 1
